# Generated by Django 5.0.6 on 2024-08-26 12:32

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[books.models.validate_age_limit], verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/books', validators=[books.models.validate_image_file_extension], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
