# Generated by Django 5.0.6 on 2024-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Полное имя')),
            ],
            options={
                'verbose_name': 'Читатели',
                'verbose_name_plural': 'Читатели',
            },
        ),
    ]
